services:
  patient-service-db:
    image: postgres:16
    container_name: patient-service-db
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - patient-service-db-data:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    build: .
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
      # - billing-service # optional, see note below
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patientdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    networks:
      - internal

volumes:
  patient-service-db-data:

networks:
  internal:
    external: true
